# Generated by Django 4.1.5 on 2023-02-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_popularmovie_movie_obj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularmovie',
            name='streamingServices',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='popularmovie',
            name='contentRating',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
