# Generated by Django 4.1.5 on 2023-02-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_popularmovie_streamingservices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularmovie',
            name='streamingServices',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
