# Generated by Django 4.1.5 on 2023-02-03 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_popularmovie_streamingservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularmovie',
            name='streamingServices',
        ),
    ]
