# Generated by Django 4.1.5 on 2023-02-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_popularmovie_streamingservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularmovie',
            name='streamingServices',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
