# Generated by Django 4.1.5 on 2023-02-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_popularmovie_countries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularmovie',
            name='fullTitle',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='popularmovie',
            name='image',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='popularmovie',
            name='movie_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
