# Generated by Django 4.1.5 on 2023-02-06 19:37

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_popularmovie_fulltitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('movie_id', models.CharField(max_length=100)),
                ('movie_img', models.ImageField(upload_to='post_images')),
                ('movie_title', models.CharField(max_length=100)),
                ('caption', models.TextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('num_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
