# Generated by Django 4.1.5 on 2023-02-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='movie_img',
        ),
        migrations.AddField(
            model_name='post',
            name='movie_img_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
