# Generated by Django 4.1.5 on 2023-02-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_post_movie_img_post_movie_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
